import { Achievement } from "@shared/schema";

export type AchievementCondition = 
  | { type: "quizzes_completed", value: number }
  | { type: "perfect_score", value: number }
  | { type: "consecutive_perfect", value: number }
  | { type: "accuracy_average", value: number, over: number }
  | { type: "accuracy_with_score", accuracy: number, minScore: number }
  | { type: "questions_answered", value: number }
  | { type: "quizzes_in_day", value: number }
  | { type: "different_topics", value: number }
  | { type: "questions_in_topic", value: number, topic: string }
  | { type: "streak_days", value: number }
  | { type: "study_time", value: number }
  | { type: "leaderboard_position", value: number }
  | { type: "leaderboard_rank_one", value: boolean }
  | { type: "users_beaten", value: number }
  | { type: "quiz_time", maxTime: number, minQuestions: number, minAccuracy: number }
  | { type: "improvement", value: number }
  | { type: "exact_score", value: number }
  | { type: "study_hour", hour: number, days: number };

export const ACHIEVEMENT_DEFINITIONS: Omit<Achievement, never>[] = [
  // STUDY MILESTONES - Common to Rare
  {
    id: "first_steps",
    name: "First Steps",
    description: "Complete your first quiz",
    category: "milestone",
    rarity: "common",
    icon: "🎯",
    condition: { type: "quizzes_completed", value: 1 },
  },
  {
    id: "getting_started",
    name: "Getting Started",
    description: "Complete 10 quizzes",
    category: "milestone",
    rarity: "common",
    icon: "📚",
    condition: { type: "quizzes_completed", value: 10 },
  },
  {
    id: "dedicated_learner",
    name: "Dedicated Learner",
    description: "Complete 50 quizzes",
    category: "milestone",
    rarity: "uncommon",
    icon: "📖",
    condition: { type: "quizzes_completed", value: 50 },
  },
  {
    id: "study_master",
    name: "Study Master",
    description: "Complete 100 quizzes",
    category: "milestone",
    rarity: "rare",
    icon: "🎓",
    condition: { type: "quizzes_completed", value: 100 },
  },
  {
    id: "legend",
    name: "Legend",
    description: "Complete 500 quizzes",
    category: "milestone",
    rarity: "legendary",
    icon: "👑",
    condition: { type: "quizzes_completed", value: 500 },
  },
  {
    id: "topic_explorer",
    name: "Topic Explorer",
    description: "Study 5 different topics",
    category: "milestone",
    rarity: "common",
    icon: "🗺️",
    condition: { type: "different_topics", value: 5 },
  },
  {
    id: "renaissance_mind",
    name: "Renaissance Mind",
    description: "Study 20 different topics",
    category: "milestone",
    rarity: "epic",
    icon: "🧠",
    condition: { type: "different_topics", value: 20 },
  },

  // ACCURACY & PERFORMANCE - Common to Legendary
  {
    id: "perfect_score",
    name: "Perfect Score",
    description: "Get 100% on any quiz",
    category: "accuracy",
    rarity: "common",
    icon: "⭐",
    condition: { type: "perfect_score", value: 1 },
  },
  {
    id: "perfectionist",
    name: "Perfectionist",
    description: "Get 100% on 5 quizzes",
    category: "accuracy",
    rarity: "uncommon",
    icon: "💫",
    condition: { type: "perfect_score", value: 5 },
  },
  {
    id: "flawless",
    name: "Flawless",
    description: "Get 100% on 10 consecutive quizzes",
    category: "accuracy",
    rarity: "epic",
    icon: "💎",
    condition: { type: "consecutive_perfect", value: 10 },
  },
  {
    id: "sharp_mind",
    name: "Sharp Mind",
    description: "Maintain 90%+ average over 20 quizzes",
    category: "accuracy",
    rarity: "rare",
    icon: "🧩",
    condition: { type: "accuracy_average", value: 90, over: 20 },
  },
  {
    id: "genius",
    name: "Genius",
    description: "Score 95%+ on a 20-question quiz",
    category: "accuracy",
    rarity: "rare",
    icon: "🌟",
    condition: { type: "accuracy_with_score", accuracy: 95, minScore: 19 },
  },
  {
    id: "quick_thinker",
    name: "Quick Thinker",
    description: "Complete quiz in under 2 minutes with 90%+",
    category: "speed",
    rarity: "uncommon",
    icon: "⚡",
    condition: { type: "quiz_time", maxTime: 120, minQuestions: 10, minAccuracy: 90 },
  },

  // STREAKS & CONSISTENCY - Uncommon to Legendary
  {
    id: "week_warrior",
    name: "Week Warrior",
    description: "7-day study streak",
    category: "streak",
    rarity: "uncommon",
    icon: "🔥",
    condition: { type: "streak_days", value: 7 },
  },
  {
    id: "month_master",
    name: "Month Master",
    description: "30-day study streak",
    category: "streak",
    rarity: "rare",
    icon: "🔥",
    condition: { type: "streak_days", value: 30 },
  },
  {
    id: "unstoppable",
    name: "Unstoppable",
    description: "100-day study streak",
    category: "streak",
    rarity: "epic",
    icon: "🔥",
    condition: { type: "streak_days", value: 100 },
  },
  {
    id: "golden_streak",
    name: "Golden Streak",
    description: "Never miss a day for 365 days",
    category: "streak",
    rarity: "legendary",
    icon: "🏆",
    condition: { type: "streak_days", value: 365 },
  },
  {
    id: "morning_scholar",
    name: "Morning Scholar",
    description: "Study 7 days in a row before 9am",
    category: "streak",
    rarity: "rare",
    icon: "🌅",
    condition: { type: "study_hour", hour: 9, days: 7 },
  },
  {
    id: "night_owl",
    name: "Night Owl",
    description: "Study 7 days in a row after 10pm",
    category: "streak",
    rarity: "rare",
    icon: "🦉",
    condition: { type: "study_hour", hour: 22, days: 7 },
  },

  // VOLUME & DEDICATION - Common to Epic
  {
    id: "question_crusher",
    name: "Question Crusher",
    description: "Answer 100 questions",
    category: "volume",
    rarity: "common",
    icon: "💪",
    condition: { type: "questions_answered", value: 100 },
  },
  {
    id: "answer_machine",
    name: "Answer Machine",
    description: "Answer 1,000 questions",
    category: "volume",
    rarity: "rare",
    icon: "🤖",
    condition: { type: "questions_answered", value: 1000 },
  },
  {
    id: "quiz_marathon",
    name: "Quiz Marathon",
    description: "Complete 10 quizzes in one day",
    category: "volume",
    rarity: "uncommon",
    icon: "🏃",
    condition: { type: "quizzes_in_day", value: 10 },
  },
  {
    id: "study_session",
    name: "Study Session",
    description: "Study for 30 minutes straight",
    category: "volume",
    rarity: "common",
    icon: "⏰",
    condition: { type: "study_time", value: 30 },
  },
  {
    id: "deep_dive",
    name: "Deep Dive",
    description: "Complete 50 questions on single topic",
    category: "volume",
    rarity: "uncommon",
    icon: "🏊",
    condition: { type: "questions_in_topic", value: 50, topic: "any" },
  },

  // IMPROVEMENT & GROWTH - Uncommon to Rare
  {
    id: "rising_star",
    name: "Rising Star",
    description: "Improve score by 20% on same topic",
    category: "improvement",
    rarity: "uncommon",
    icon: "📈",
    condition: { type: "improvement", value: 20 },
  },
  {
    id: "comeback_kid",
    name: "Comeback Kid",
    description: "Score 90%+ after getting below 50%",
    category: "improvement",
    rarity: "uncommon",
    icon: "🎯",
    condition: { type: "improvement", value: 40 },
  },
  {
    id: "mastery",
    name: "Mastery",
    description: "Go from 60% to 95%+ on a topic",
    category: "improvement",
    rarity: "rare",
    icon: "🏅",
    condition: { type: "improvement", value: 35 },
  },

  // LEADERBOARD & SOCIAL - Uncommon to Epic
  {
    id: "top_ten",
    name: "Top 10",
    description: "Reach top 10 on leaderboard",
    category: "leaderboard",
    rarity: "uncommon",
    icon: "🥉",
    condition: { type: "leaderboard_position", value: 10 },
  },
  {
    id: "top_five",
    name: "Top 5",
    description: "Reach top 5 on leaderboard",
    category: "leaderboard",
    rarity: "rare",
    icon: "🥈",
    condition: { type: "leaderboard_position", value: 5 },
  },
  {
    id: "number_one",
    name: "#1 Spot",
    description: "Reach #1 on leaderboard",
    category: "leaderboard",
    rarity: "epic",
    icon: "🥇",
    condition: { type: "leaderboard_rank_one", value: true },
  },
  {
    id: "competitive",
    name: "Competitive",
    description: "Beat 10 different users' scores",
    category: "leaderboard",
    rarity: "uncommon",
    icon: "⚔️",
    condition: { type: "users_beaten", value: 10 },
  },

  // SPEED - Common to Rare
  {
    id: "lightning_fast",
    name: "Lightning Fast",
    description: "Complete 10-question quiz in under 60 seconds",
    category: "speed",
    rarity: "uncommon",
    icon: "⚡",
    condition: { type: "quiz_time", maxTime: 60, minQuestions: 10, minAccuracy: 70 },
  },
  {
    id: "speed_demon",
    name: "Speed Demon",
    description: "Answer 100 questions in under 10 minutes",
    category: "speed",
    rarity: "rare",
    icon: "🏎️",
    condition: { type: "quiz_time", maxTime: 600, minQuestions: 100, minAccuracy: 75 },
  },

  // FUN & QUIRKY - Common to Rare
  {
    id: "lucky_sevens",
    name: "Lucky Number Seven",
    description: "Score exactly 77%",
    category: "fun",
    rarity: "uncommon",
    icon: "🎰",
    condition: { type: "exact_score", value: 77 },
  },
  {
    id: "perfectionist_100",
    name: "Century",
    description: "Score exactly 100 points",
    category: "fun",
    rarity: "uncommon",
    icon: "💯",
    condition: { type: "exact_score", value: 100 },
  },
  {
    id: "midnight_scholar",
    name: "Midnight Scholar",
    description: "Complete quiz at exactly midnight",
    category: "fun",
    rarity: "rare",
    icon: "🌙",
    condition: { type: "study_hour", hour: 0, days: 1 },
  },

  // SPECIAL - Epic to Legendary
  {
    id: "early_adopter",
    name: "Early Adopter",
    description: "One of the first 100 users",
    category: "special",
    rarity: "epic",
    icon: "🌱",
    condition: { type: "quizzes_completed", value: 1 },
  },
  {
    id: "perfect_week",
    name: "Perfect Week",
    description: "100% accuracy on all quizzes for 7 days",
    category: "special",
    rarity: "legendary",
    icon: "✨",
    condition: { type: "consecutive_perfect", value: 50 },
  },

  // ADDITIONAL MILESTONES
  {
    id: "milestone_5",
    name: "Starter Pack",
    description: "Complete 5 quizzes",
    category: "milestone",
    rarity: "common",
    icon: "🎪",
    condition: { type: "quizzes_completed", value: 5 },
  },
  {
    id: "milestone_25",
    name: "Quarter Century",
    description: "Complete 25 quizzes",
    category: "milestone",
    rarity: "common",
    icon: "🎨",
    condition: { type: "quizzes_completed", value: 25 },
  },
  {
    id: "milestone_75",
    name: "Advanced Scholar",
    description: "Complete 75 quizzes",
    category: "milestone",
    rarity: "uncommon",
    icon: "🎭",
    condition: { type: "quizzes_completed", value: 75 },
  },
  {
    id: "milestone_200",
    name: "Quiz Veteran",
    description: "Complete 200 quizzes",
    category: "milestone",
    rarity: "rare",
    icon: "🎖️",
    condition: { type: "quizzes_completed", value: 200 },
  },
  {
    id: "milestone_300",
    name: "Elite Learner",
    description: "Complete 300 quizzes",
    category: "milestone",
    rarity: "epic",
    icon: "👨‍🎓",
    condition: { type: "quizzes_completed", value: 300 },
  },
  {
    id: "milestone_1000",
    name: "Quiz Legend",
    description: "Complete 1,000 quizzes",
    category: "milestone",
    rarity: "legendary",
    icon: "🦸",
    condition: { type: "quizzes_completed", value: 1000 },
  },
  {
    id: "topic_3",
    name: "Curious Mind",
    description: "Study 3 different topics",
    category: "milestone",
    rarity: "common",
    icon: "🔍",
    condition: { type: "different_topics", value: 3 },
  },
  {
    id: "topic_10",
    name: "Knowledge Seeker",
    description: "Study 10 different topics",
    category: "milestone",
    rarity: "uncommon",
    icon: "🎯",
    condition: { type: "different_topics", value: 10 },
  },
  {
    id: "topic_15",
    name: "Polymath",
    description: "Study 15 different topics",
    category: "milestone",
    rarity: "rare",
    icon: "🌐",
    condition: { type: "different_topics", value: 15 },
  },
  {
    id: "topic_30",
    name: "Universal Scholar",
    description: "Study 30 different topics",
    category: "milestone",
    rarity: "legendary",
    icon: "🌌",
    condition: { type: "different_topics", value: 30 },
  },

  // ADDITIONAL ACCURACY ACHIEVEMENTS
  {
    id: "accurate_10",
    name: "Good Start",
    description: "Get 80%+ on 10 quizzes",
    category: "accuracy",
    rarity: "common",
    icon: "🎯",
    condition: { type: "accuracy_average", value: 80, over: 10 },
  },
  {
    id: "accurate_50",
    name: "Consistent Performer",
    description: "Get 85%+ average over 50 quizzes",
    category: "accuracy",
    rarity: "uncommon",
    icon: "🎪",
    condition: { type: "accuracy_average", value: 85, over: 50 },
  },
  {
    id: "perfect_10",
    name: "Perfect Ten",
    description: "Get 100% on 10 quizzes",
    category: "accuracy",
    rarity: "rare",
    icon: "🌟",
    condition: { type: "perfect_score", value: 10 },
  },
  {
    id: "perfect_25",
    name: "Perfection Master",
    description: "Get 100% on 25 quizzes",
    category: "accuracy",
    rarity: "epic",
    icon: "💠",
    condition: { type: "perfect_score", value: 25 },
  },
  {
    id: "perfect_50",
    name: "Flawless Champion",
    description: "Get 100% on 50 quizzes",
    category: "accuracy",
    rarity: "legendary",
    icon: "💫",
    condition: { type: "perfect_score", value: 50 },
  },
  {
    id: "consecutive_3",
    name: "Hat Trick",
    description: "Get 100% on 3 consecutive quizzes",
    category: "accuracy",
    rarity: "common",
    icon: "🎩",
    condition: { type: "consecutive_perfect", value: 3 },
  },
  {
    id: "consecutive_5",
    name: "Perfect Streak",
    description: "Get 100% on 5 consecutive quizzes",
    category: "accuracy",
    rarity: "uncommon",
    icon: "✨",
    condition: { type: "consecutive_perfect", value: 5 },
  },

  // ADDITIONAL STREAK ACHIEVEMENTS
  {
    id: "streak_3",
    name: "Starting Strong",
    description: "3-day study streak",
    category: "streak",
    rarity: "common",
    icon: "🔥",
    condition: { type: "streak_days", value: 3 },
  },
  {
    id: "streak_14",
    name: "Two Weeks",
    description: "14-day study streak",
    category: "streak",
    rarity: "uncommon",
    icon: "🔥",
    condition: { type: "streak_days", value: 14 },
  },
  {
    id: "streak_60",
    name: "Two Months",
    description: "60-day study streak",
    category: "streak",
    rarity: "rare",
    icon: "🔥",
    condition: { type: "streak_days", value: 60 },
  },
  {
    id: "streak_180",
    name: "Half Year Hero",
    description: "180-day study streak",
    category: "streak",
    rarity: "epic",
    icon: "🔥",
    condition: { type: "streak_days", value: 180 },
  },
  {
    id: "weekend_warrior",
    name: "Weekend Warrior",
    description: "Study every weekend for a month",
    category: "streak",
    rarity: "uncommon",
    icon: "⚔️",
    condition: { type: "streak_days", value: 4 },
  },

  // ADDITIONAL VOLUME ACHIEVEMENTS
  {
    id: "questions_50",
    name: "Question Starter",
    description: "Answer 50 questions",
    category: "volume",
    rarity: "common",
    icon: "📝",
    condition: { type: "questions_answered", value: 50 },
  },
  {
    id: "questions_250",
    name: "Answer Pro",
    description: "Answer 250 questions",
    category: "volume",
    rarity: "uncommon",
    icon: "📋",
    condition: { type: "questions_answered", value: 250 },
  },
  {
    id: "questions_500",
    name: "Question Expert",
    description: "Answer 500 questions",
    category: "volume",
    rarity: "uncommon",
    icon: "📊",
    condition: { type: "questions_answered", value: 500 },
  },
  {
    id: "questions_2500",
    name: "Answer Champion",
    description: "Answer 2,500 questions",
    category: "volume",
    rarity: "rare",
    icon: "🏆",
    condition: { type: "questions_answered", value: 2500 },
  },
  {
    id: "questions_5000",
    name: "Knowledge Powerhouse",
    description: "Answer 5,000 questions",
    category: "volume",
    rarity: "epic",
    icon: "⚡",
    condition: { type: "questions_answered", value: 5000 },
  },
  {
    id: "daily_5",
    name: "Daily Driver",
    description: "Complete 5 quizzes in one day",
    category: "volume",
    rarity: "common",
    icon: "🚗",
    condition: { type: "quizzes_in_day", value: 5 },
  },
  {
    id: "daily_15",
    name: "Quiz Grinder",
    description: "Complete 15 quizzes in one day",
    category: "volume",
    rarity: "rare",
    icon: "⚙️",
    condition: { type: "quizzes_in_day", value: 15 },
  },
  {
    id: "daily_20",
    name: "Beast Mode",
    description: "Complete 20 quizzes in one day",
    category: "volume",
    rarity: "epic",
    icon: "🦁",
    condition: { type: "quizzes_in_day", value: 20 },
  },
  {
    id: "study_60",
    name: "Hour of Power",
    description: "Study for 60 minutes",
    category: "volume",
    rarity: "uncommon",
    icon: "⏰",
    condition: { type: "study_time", value: 60 },
  },
  {
    id: "study_120",
    name: "Study Beast",
    description: "Study for 120 minutes",
    category: "volume",
    rarity: "rare",
    icon: "🦾",
    condition: { type: "study_time", value: 120 },
  },
  {
    id: "study_300",
    name: "Marathon Learner",
    description: "Study for 5 hours straight",
    category: "volume",
    rarity: "epic",
    icon: "🏃‍♂️",
    condition: { type: "study_time", value: 300 },
  },

  // ADDITIONAL IMPROVEMENT ACHIEVEMENTS
  {
    id: "improvement_10",
    name: "Getting Better",
    description: "Improve score by 10% on same topic",
    category: "improvement",
    rarity: "common",
    icon: "📈",
    condition: { type: "improvement", value: 10 },
  },
  {
    id: "improvement_30",
    name: "Major Progress",
    description: "Improve score by 30% on same topic",
    category: "improvement",
    rarity: "uncommon",
    icon: "🚀",
    condition: { type: "improvement", value: 30 },
  },
  {
    id: "improvement_50",
    name: "Transformation",
    description: "Improve score by 50% on same topic",
    category: "improvement",
    rarity: "rare",
    icon: "🌱",
    condition: { type: "improvement", value: 50 },
  },
  {
    id: "from_zero_hero",
    name: "From Zero to Hero",
    description: "Go from 0% to 100% on a topic",
    category: "improvement",
    rarity: "epic",
    icon: "🦸‍♂️",
    condition: { type: "improvement", value: 100 },
  },

  // ADDITIONAL LEADERBOARD ACHIEVEMENTS
  {
    id: "top_25",
    name: "Top 25",
    description: "Reach top 25 on leaderboard",
    category: "leaderboard",
    rarity: "common",
    icon: "🏅",
    condition: { type: "leaderboard_position", value: 25 },
  },
  {
    id: "top_3",
    name: "Podium Finish",
    description: "Reach top 3 on leaderboard",
    category: "leaderboard",
    rarity: "rare",
    icon: "🥉",
    condition: { type: "leaderboard_position", value: 3 },
  },
  {
    id: "users_5",
    name: "Beginner Competitor",
    description: "Beat 5 different users' scores",
    category: "leaderboard",
    rarity: "common",
    icon: "⚔️",
    condition: { type: "users_beaten", value: 5 },
  },
  {
    id: "users_25",
    name: "Rival Crusher",
    description: "Beat 25 different users' scores",
    category: "leaderboard",
    rarity: "rare",
    icon: "🗡️",
    condition: { type: "users_beaten", value: 25 },
  },
  {
    id: "users_50",
    name: "Leaderboard Dominator",
    description: "Beat 50 different users' scores",
    category: "leaderboard",
    rarity: "epic",
    icon: "👊",
    condition: { type: "users_beaten", value: 50 },
  },

  // ADDITIONAL SPEED ACHIEVEMENTS
  {
    id: "speed_5min",
    name: "Quick Quiz",
    description: "Complete quiz in under 5 minutes with 80%+",
    category: "speed",
    rarity: "common",
    icon: "💨",
    condition: { type: "quiz_time", maxTime: 300, minQuestions: 10, minAccuracy: 80 },
  },
  {
    id: "speed_3min",
    name: "Rapid Fire",
    description: "Complete 15-question quiz in under 3 minutes",
    category: "speed",
    rarity: "uncommon",
    icon: "🎯",
    condition: { type: "quiz_time", maxTime: 180, minQuestions: 15, minAccuracy: 80 },
  },
  {
    id: "speed_master",
    name: "Speed Master",
    description: "Complete 20-question quiz in under 2 minutes",
    category: "speed",
    rarity: "rare",
    icon: "🏎️",
    condition: { type: "quiz_time", maxTime: 120, minQuestions: 20, minAccuracy: 85 },
  },
  {
    id: "flash_learner",
    name: "Flash Learner",
    description: "Answer 50 questions in under 5 minutes",
    category: "speed",
    rarity: "epic",
    icon: "⚡",
    condition: { type: "quiz_time", maxTime: 300, minQuestions: 50, minAccuracy: 80 },
  },

  // ADDITIONAL FUN ACHIEVEMENTS
  {
    id: "half_century",
    name: "Half Century",
    description: "Score exactly 50%",
    category: "fun",
    rarity: "common",
    icon: "🎲",
    condition: { type: "exact_score", value: 50 },
  },
  {
    id: "lucky_13",
    name: "Lucky 13",
    description: "Score exactly 13 points",
    category: "fun",
    rarity: "uncommon",
    icon: "🍀",
    condition: { type: "exact_score", value: 13 },
  },
  {
    id: "perfect_69",
    name: "Nice",
    description: "Score exactly 69%",
    category: "fun",
    rarity: "uncommon",
    icon: "😎",
    condition: { type: "exact_score", value: 69 },
  },
  {
    id: "triple_three",
    name: "Triple Three",
    description: "Score exactly 33%",
    category: "fun",
    rarity: "uncommon",
    icon: "3️⃣",
    condition: { type: "exact_score", value: 33 },
  },
  {
    id: "breakfast_club",
    name: "Breakfast Club",
    description: "Study at 7am for 3 days in a row",
    category: "fun",
    rarity: "uncommon",
    icon: "🥞",
    condition: { type: "study_hour", hour: 7, days: 3 },
  },
  {
    id: "lunch_learner",
    name: "Lunch Learner",
    description: "Study at noon for 5 days",
    category: "fun",
    rarity: "uncommon",
    icon: "🍽️",
    condition: { type: "study_hour", hour: 12, days: 5 },
  },
  {
    id: "witching_hour",
    name: "Witching Hour",
    description: "Study at 3am",
    category: "fun",
    rarity: "rare",
    icon: "🧙",
    condition: { type: "study_hour", hour: 3, days: 1 },
  },

  // ADDITIONAL SPECIAL ACHIEVEMENTS
  {
    id: "first_user",
    name: "Pioneer",
    description: "One of the first 10 users",
    category: "special",
    rarity: "legendary",
    icon: "🌟",
    condition: { type: "quizzes_completed", value: 1 },
  },
  {
    id: "beta_tester",
    name: "Beta Tester",
    description: "One of the first 50 users",
    category: "special",
    rarity: "epic",
    icon: "🧪",
    condition: { type: "quizzes_completed", value: 1 },
  },
  {
    id: "comeback",
    name: "Comeback Story",
    description: "Return after 30 days absence",
    category: "special",
    rarity: "uncommon",
    icon: "🔄",
    condition: { type: "quizzes_completed", value: 999999 },
  },
  {
    id: "dedication",
    name: "True Dedication",
    description: "Study every single day for a month",
    category: "special",
    rarity: "epic",
    icon: "💪",
    condition: { type: "streak_days", value: 30 },
  },
  {
    id: "night_shift",
    name: "Night Shift",
    description: "Complete 10 quizzes between midnight and 5am",
    category: "special",
    rarity: "rare",
    icon: "🌃",
    condition: { type: "quizzes_completed", value: 10 },
  },
  {
    id: "weekend_grind",
    name: "Weekend Grind",
    description: "Complete 50 quizzes on weekends only",
    category: "special",
    rarity: "uncommon",
    icon: "📅",
    condition: { type: "quizzes_completed", value: 50 },
  },

  // FINAL 3 ACHIEVEMENTS TO REACH 100
  {
    id: "quiz_addict",
    name: "Quiz Addict",
    description: "Complete 25 quizzes in a single day",
    category: "volume",
    rarity: "legendary",
    icon: "🎮",
    condition: { type: "quizzes_in_day", value: 25 },
  },
  {
    id: "knowledge_vault",
    name: "Knowledge Vault",
    description: "Answer 10,000 questions",
    category: "volume",
    rarity: "legendary",
    icon: "📚",
    condition: { type: "questions_answered", value: 10000 },
  },
  {
    id: "ultimate_scholar",
    name: "Ultimate Scholar",
    description: "Complete 2,000 quizzes",
    category: "milestone",
    rarity: "legendary",
    icon: "🏆",
    condition: { type: "quizzes_completed", value: 2000 },
  },
];

export function getRarityColor(rarity: string): string {
  switch (rarity) {
    case "common":
      return "text-gray-400 dark:text-gray-500";
    case "uncommon":
      return "text-green-500 dark:text-green-400";
    case "rare":
      return "text-blue-500 dark:text-blue-400";
    case "epic":
      return "text-purple-500 dark:text-purple-400";
    case "legendary":
      return "text-yellow-500 dark:text-yellow-400";
    default:
      return "text-gray-400";
  }
}

export function getRarityBadgeColor(rarity: string): string {
  switch (rarity) {
    case "common":
      return "bg-gray-100 dark:bg-gray-800 text-gray-700 dark:text-gray-300";
    case "uncommon":
      return "bg-green-100 dark:bg-green-900 text-green-700 dark:text-green-300";
    case "rare":
      return "bg-blue-100 dark:bg-blue-900 text-blue-700 dark:text-blue-300";
    case "epic":
      return "bg-purple-100 dark:bg-purple-900 text-purple-700 dark:text-purple-300";
    case "legendary":
      return "bg-gradient-to-r from-yellow-400 to-orange-500 text-white";
    default:
      return "bg-gray-100 dark:bg-gray-800 text-gray-700 dark:text-gray-300";
  }
}
